### PR TITLE
Resolved issue with deleting queries

### LINKED ISSUE #268: DeserializationError during initial migration
When running `syncdb --migrate` the following error is seen:

```
> varify:0002_avocado_metadata_migration
> varify:0003_fix_sequence_problems
- Loading initial data for varify.
Problem installing fixture 'varify/fixtures/initial_data.json': Traceback (most recent call last):
  File "/Users/ohara/varify-env/lib/python2.7/site-packages/django/core/management/commands/http://loaddata.py", line 190, in handle
    for obj in objects:
  File "/Users/ohara/varify-env/lib/python2.7/site-packages/django/core/serializers/http://json.py", line 47, in Deserializer
    raise DeserializationError(e)
DeserializationError: ContentType matching query does not exist.
```

### PR DESCRIPTION
**Pull request by hassanNS**
Fix #268
The issue correcting `main.js` to register the deleteQuery function.

Signed-off-by: Sheik Hassan solergiga@yahoo.com

### CODE REVIEW

File: varify/static/js/src/main.js [hunk 1]
```diff
@@ -179,6 +179,12 @@ require({
                     collection: this.data.queries
                 }),
 
+                deleteQuery: new c.ui.DeleteQueryDialog({
```
Comment (naegelyd) [inline varify/static/js/src/main.js]: DeleteQueryDialog does not require any options. See [Cilantro's registration](https://github.com/cbmi/cilantro/blob/master/src/js/cilantro/main.js#L70) as the example.
